Improve posts
Isaac-A-UofT/207-final-project pull request #45
Opened 2023-11-29 16:51 UTC by lawrencef2

Updated validation and implemented email and timestamps for posts

2023-11-29 17:16 UTC, Isaac-A-UofT requested changes

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/CreatePostController.java
> +                                        @RequestParam String email) {
Test to make sure this format works for a POST request.

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/CreatePostService.java
> +                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
Remove this for running in EC2

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/CreatePostService.java
> +        AWSCredentials awsCredentials = new BasicAWSCredentials("", "");
Remove for running in EC2

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/Post.java
> +        TimeZone tz = TimeZone.getTimeZone("UTC");
We're in toronto, why not EST?

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/PostCriteria.java
> +            String token = validateUserApi.validateUser(username, StringEncrypter.decrypt(password));
Is password encrypted?

2023-11-29 17:16 UTC, Isaac-A-UofT commented on backend/src/main/java/thestudentbase/backend/PostCriteria.java
> +            String token = validateUserApi.validateUser(username, StringEncrypter.decrypt(password));
also, I thought, we werent using password anymore

2023-11-30 06:10 UTC, lawrencef2 commented on backend/src/main/java/thestudentbase/backend/Post.java
> +        TimeZone tz = TimeZone.getTimeZone("UTC");
I would use EST, however the format for timestamps that works with the ISO standard uses UTC by default, and it would be easier to have everything use UTC.

2023-11-30 06:11 UTC, lawrencef2 commented on backend/src/main/java/thestudentbase/backend/PostCriteria.java
> +            String token = validateUserApi.validateUser(username, StringEncrypter.decrypt(password));
We still need password to call the validateUser method, and we're assuming that password is encrypted when we receive it

2023-12-01 03:59 UTC, merged