Changed login and validateuser to better follow CA
Isaac-A-UofT/207-final-project pull request #48
Opened 2023-11-30 21:10 UTC by KFPTartman

There are a few places that I'm not sure if I'm doing the correct things so let me know what you think. Below are some of the things that worry me

- In loginController, I call outputdata.getresponse() to send the ResponseEntity but is that ok in terms of CA stuff?
- I made is so that me thod validateUser in use case interactor returns null for invalid users but would that be ok as other classes also call validateUser?

2023-11-30 21:44 UTC, Kavirajgaire requested changes
Overall, the code looks correct, is well documented and follows CA. I think the naming and overall structure still need work. Instead of putting it into one folder they should be separated by database, entities, use case interator, etc. I think the naming is also confusing, what makes something login and something else validate user? This should just be all under the login name with validate user being the name of a method and not any file.

2023-11-30 21:44 UTC, Kavirajgaire commented on backend/src/main/java/thestudentbase/backend/login_and_validateuser/ValidateUserApi.java
This file is Unnecessary since it is just comments.

2023-11-30 21:44 UTC, Kavirajgaire commented on backend/src/main/java/thestudentbase/backend/login_and_validateuser/validateuserdatabaseobject.java
>              AWSCognitoIdentityProvider cognitoClient = AWSCognitoIdentityProviderClientBuilder.standard()
Move any AWS builders to the DBConfig file

2023-12-01 01:57 UTC, KFPTartman commented on backend/src/main/java/thestudentbase/backend/login_and_validateuser/validateuserdatabaseobject.java
>              AWSCognitoIdentityProvider cognitoClient = AWSCognitoIdentityProviderClientBuilder.standard()
What do you mean by DBConfig file? Is it the data_access file?

2023-12-01 03:34 UTC, Kavirajgaire approved these changes
Looks good to merge now.

2023-12-01 03:49 UTC, merged